/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sortdictionary;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;

/**
 *
 * @author jan
 */
public class Dictionary extends javax.swing.JFrame {

    ArrayList<String> al = new ArrayList();
    String dizi[];

    /**
     * Creates new form Dictionary
     */
    public Dictionary() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(jRadioButton1);
        group.add(jRadioButton2);
        group.add(jRadioButton3);
        group.add(jRadioButton4);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Open File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sort");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Bubble Sort");

        jRadioButton2.setText("Selection Sort");

        jRadioButton3.setText("Insertion Sort");

        jRadioButton4.setText("Quick Sort");

        jLabel1.setText("After Sorting");

        jLabel2.setText("Results (Ms)");

        jLabel3.setText("Bubble Sort");

        jLabel4.setText("Selection Sort");

        jLabel5.setText("Insertion Sort");

        jLabel6.setText("Quick Sort");

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        File file = null;
        Component component = null;
        if (fileChooser.showOpenDialog(component) == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
        }

        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(file));
        } catch (FileNotFoundException ex) {
            System.out.println("Dosya yok");
        }
        String s = "";
        try {
            while ((s = br.readLine()) != null) {
                //jTextArea1.setText(jTextArea1.getText() + "\n" +s);
                al.add(s);
            }
        } catch (IOException ex) {
            Logger.getLogger(Dictionary.class.getName()).log(Level.SEVERE, null, ex);
        }
        arrayListToString(al);
    }//GEN-LAST:event_jButton1ActionPerformed

    void arrayListToString(ArrayList<String> al) {
        dizi = new String[al.size()];
        for (int i = 0; i < al.size(); i++) {
            dizi[i] = al.get(i);
        }
    }
    
    void printDizi(String[] dizi){
        jList1.setListData(dizi);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
            long basla = System.nanoTime();
            bubbleSort(dizi);
            long bitis = System.nanoTime();
            double zaman = (bitis-basla)/1000000.0;
            jLabel3.setText(jLabel3.getText() + "     " + String.valueOf(zaman));
            printDizi(dizi);
        } else if (jRadioButton2.isSelected()) {
            long basla = System.nanoTime();
            selectionSort(dizi);
            long bitis = System.nanoTime();
            double zaman = (bitis-basla)/1000000.0;
            jLabel4.setText(jLabel4.getText() + "     " + String.valueOf(zaman));
            printDizi(dizi);
        } else if (jRadioButton3.isSelected()) {
            long basla = System.nanoTime();
            insertionSort(dizi);
            long bitis = System.nanoTime();
            double zaman = (bitis-basla)/1000000.0;
            jLabel5.setText(jLabel5.getText() + "     " + String.valueOf(zaman));
            printDizi(dizi);
        } else if (jRadioButton4.isSelected()) {
            long basla = System.nanoTime();
            quickSort(dizi, 0, dizi.length - 1);
            long bitis = System.nanoTime();
            double zaman = (bitis-basla)/1000000.0;
            jLabel6.setText(jLabel6.getText() + "     " + String.valueOf(zaman));
            printDizi(dizi);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    static void bubbleSort(String[] dizi) {
        for (int i = dizi.length; i > 1; i--) {
            for (int j = 0; j < i - 1; j++) {
                if (dizi[j].compareTo(dizi[j + 1]) > 0) {
                    String s = dizi[j];
                    dizi[j] = dizi[j + 1];
                    dizi[j + 1] = s;
                }
            }
        }
    }

    static void selectionSort(String[] dizi) {
        String min = "";
        int swap = 0;
        for (int i = 0; i < dizi.length; i++) {
            min = dizi[i];
            for (int j = i + 1; j < dizi.length; j++) {
                if (min.compareTo(dizi[j]) > 0) {
                    min = dizi[j];
                    swap = j;
                }
            }
            String s = dizi[i];
            dizi[i] = dizi[swap];
            dizi[swap] = s;
        }
    }

    static void insertionSort(String[] dizi) {
        for (int i = 1; i < dizi.length; i++) {
            int say = i;
            for (int j = i; j >= 0; j--) {
                if (dizi[say].compareTo(dizi[j]) < 0) {
                    String s = dizi[j];
                    dizi[j] = dizi[say];
                    dizi[say] = s;
                    say = say - 1;
                }
            }
        }
    }
    
    static void quickSort(String[] dizi, int basla, int bitis){
        int i = basla;
        int j = bitis;

        if (j - i >= 1){
            String pivot = dizi[i];
            while (j > i){
                while (dizi[i].compareTo(pivot) <= 0 && i < bitis && j > i){
                    i++;
                }
                while (dizi[j].compareTo(pivot) >= 0 && j > basla && j >= i){
                    j--;
                }
                if (j > i){
                    String s = dizi[i];
                    dizi[i] = dizi[j];
                    dizi[j] = s;
                }                    
            }
            String s = dizi[basla];
            dizi[basla] = dizi[j];
            dizi[j] = s;
            
            quickSort(dizi, basla, j - 1);
            quickSort(dizi, j + 1, bitis);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dictionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
